#!/bin/bash
trashdir=~/.trash/
list=$trashdir.list.txt
no_args=true

 Help()
{
   # Display Help
   echo "move specified files to ~/.trash"
   echo
   echo "Syntax: trash [options] [arg] [files]"
   echo "options:"
   echo "   -h      show help"
   echo "   -P      Purge trash directory,"
   echo "            remove files older than [arg]days"
   echo "   -a      ask for each file before purging" 
}

Delete()
{

    # find files older than $days
    find $trashdir -ctime +$days > $list
    echo do you realy want to delete:
    cat $list
    while true; do
	read -p "y/n :" dlt
	if [ $dlt = "y" ]; then
	    rm $1 $(cat $list)
	    break
	elif [ $dlt = "n" ]; then
	    break
	else
	    echo $dlt is not a valid choice
	fi
    done
}

# Handle the options passed with -
while getopts ":hP:a:" option; do
    case $option in
        h) # display Help
            Help
            exit;;
        P) # delete old files
	    # attribute the argument to days
            days=$OPTARG
	    Delete 
	    exit;;
        a) # delete old files
	    # attribute the argument to days
            days=$OPTARG
	    Delete -i 
	    exit;;
    esac
    no_args=false
done

if $no_args; then
    dirname=$(pwd)
    mkdir -p $trashdir$dirname
    for filename in $@; do
        mv $filename ~/.trash$dirname
        echo moved $filename to ~/.trash$dirname
    done
fi

